/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface CustomDialog {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCustomDialogElement extends Components.CustomDialog, HTMLStencilElement {
    }
    var HTMLCustomDialogElement: {
        prototype: HTMLCustomDialogElement;
        new (): HTMLCustomDialogElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "custom-dialog": HTMLCustomDialogElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface CustomDialog {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "custom-dialog": CustomDialog;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "custom-dialog": LocalJSX.CustomDialog & JSXBase.HTMLAttributes<HTMLCustomDialogElement>;
        }
    }
}
